"""Generate bit-exact regressions for bugs discovered by mass_osu.py.

Usage: python scripts/gen_mass_osu_refs.py <MassOsu.dll> [output.rs]
Build the source-based worker with mass_osu.py first. Confirm representative
outputs against the official simulate CLI before replacing these references.
"""
import json
from pathlib import Path
import subprocess
import sys

from gen_ext_refs import reference_provenance
from mass_osu import MODS, ROOT, query, worker


def pairs(values, optional=False):
    result = []
    for name, value in values.items():
        if value is None and name == "flashlight_difficulty":
            value = "0000000000000000"
        literal = "None" if value is None else f"0x{value}"
        if optional and value is not None:
            literal = f"Some({literal})"
        result.append(f'("{name}", {literal}),')
    return "\n".join(result)


def main():
    output = Path(sys.argv[2]) if len(sys.argv) > 2 else ROOT / "tests/data/mass_osu_refs.rs"
    process = worker(["dotnet", str(Path(sys.argv[1]).resolve())])
    rows = ["// GENERATED by scripts/gen_mass_osu_refs.py - do not edit by hand.", *reference_provenance(),
            "pub struct MassOsuRef { pub path: &'static str, pub mods: u32, pub lazer: bool, pub difficulty: &'static [(&'static str, u64)], pub scores: &'static [MassOsuScore] }",
            "pub struct MassOsuScore { pub state: [u32; 7], pub performance: &'static [(&'static str, Option<u64>)] }",
            "pub const MASS_OSU_REFS: &[MassOsuRef] = &["]
    try:
        for path in sorted((ROOT / "tests/data/mass_osu").glob("*.osu")):
            relative = path.relative_to(ROOT).as_posix()
            for classic in [False, True]:
                for mods in MODS:
                    ref = query(process, f"{path}\t{mods}\t{int(classic)}")
                    if "error" in ref:
                        raise RuntimeError(ref["error"])
                    rows += [f'MassOsuRef {{ path: "{relative}", mods: {mods}, lazer: {str(not classic).lower()}, difficulty: &[',
                             pairs(ref["difficulty"]), "], scores: &["]
                    for case in ref["cases"]:
                        rows += [f'MassOsuScore {{ state: {case["state"]}, performance: &[', pairs(case["performance"], True), "] },"]
                    rows += ["] },"]
    finally:
        process.stdin.close()
        process.wait(timeout=30)
    rows += ["];", ""]
    output.write_text("\n".join(rows), encoding="utf-8", newline="\n")
    subprocess.run(["rustfmt", "--edition", "2024", "--config", "newline_style=Unix", str(output)], check=True)


if __name__ == "__main__":
    main()
