"""Generate Standard classic, ScoreV2, Relax and short-map C# regression cases.

Usage: python scripts/gen_ext_edge_refs.py tests/data/ext_edge_refs.rs
OSU_TOOLS_DIR selects the osu-tools checkout, as in the other generators.
"""
import json
import subprocess
import sys
from pathlib import Path

from gen_ext_acc_refs import CLI_DIR, ROOT, fmt_perf
from gen_ext_refs import fmt_diff, reference_provenance

# name, map, Rust mod bits, CLI mods, goods, mehs, misses, combo, legacy score
CASES = [
    ("classic", "resources/2785319.osu", 0, "cl", 24, 12, 12, 448, None),
    ("classic_zero_score", "resources/2785319.osu", 0, "cl", 24, 12, 12, 448, 0),
    ("classic_legacy_score", "resources/2785319.osu", 0, "cl", 24, 12, 12, 448, 10000000),
    ("classic_flashlight", "resources/2785319.osu", 1024, "cl fl", 24, 12, 12, 448, None),
    ("score_v2", "resources/100.osu", 536870912, "cl sv2", 4, 2, 2, 110, None),
    ("score_v2_legacy_score", "resources/100.osu", 536870912, "cl sv2", 4, 2, 2, 110, 200000),
    ("low_od_relax", "tests/data/osu_low_od.osu", 128, "cl rx", 1, 0, 1, 1, None),
    ("short_map_miss", "tests/data/osu_low_od.osu", 0, "cl", 0, 0, 1, 1, None),
    ("all_misses", "tests/data/osu_low_od.osu", 0, "cl", 0, 0, 2, 0, None),
    ("empty", "tests/data/osu_empty.osu", 0, "cl", 0, 0, 0, 0, None),
]


def main():
    lines = [
        "// GENERATED by scripts/gen_ext_edge_refs.py - do not edit by hand.",
        *reference_provenance(),
        "// Classic scores use the hit-circle accuracy formula (Rust lazer(false)).",
        "pub struct ExtEdgeRef {",
        "    pub name: &'static str,",
        "    pub path: &'static str,",
        "    pub mods: u32,",
        "    pub n300: u32,",
        "    pub n100: u32,",
        "    pub n50: u32,",
        "    pub misses: u32,",
        "    pub combo: u32,",
        "    pub legacy_total_score: Option<u32>,",
        "    pub difficulty: &'static [(&'static str, &'static str)],",
        "    pub performance: &'static [(&'static str, Option<&'static str>)],",
        "}",
        "pub const EXT_EDGE_REFS: &[ExtEdgeRef] = &[",
    ]
    for name, path, flags, mods, goods, mehs, misses, combo, legacy_score in CASES:
        cmd = ["dotnet", "run", "--no-build", "--", "simulate", "osu", str(ROOT / path),
               "--goods", str(goods), "--mehs", str(mehs), "-X", str(misses),
               "--combo", str(combo), "-j"]
        for mod in mods.split():
            cmd += ["-m", mod]
        if legacy_score is not None:
            cmd += ["--legacy-total-score", str(legacy_score)]
        result = subprocess.run(cmd, cwd=CLI_DIR, capture_output=True, text=True, check=True)
        data = json.loads(result.stdout)
        score = data["score"]
        stats = score["statistics"]
        assert (stats["ok"], stats["meh"], stats["miss"], score["combo"]) == (goods, mehs, misses, combo)
        expected_mods = {mod.upper() for mod in mods.split()}
        assert {mod["acronym"].upper() for mod in score["mods"]} == expected_mods
        legacy = "None" if legacy_score is None else f"Some({legacy_score})"
        lines.append(
            f'    ExtEdgeRef {{ name: {json.dumps(name)}, path: {json.dumps(path)}, '
            f'mods: {flags}, n300: {stats["great"]}, n100: {goods}, n50: {mehs}, '
            f'misses: {misses}, combo: {combo}, legacy_total_score: {legacy}, '
            f'difficulty: &{fmt_diff(data["difficulty_attributes"])}, '
            f'performance: &{fmt_perf(data["performance_attributes"])} }},'
        )
    lines.append("];")
    out = Path(sys.argv[1])
    out.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    subprocess.run(["rustfmt", "--edition", "2024", str(out)], check=True)
    print(f"wrote {sys.argv[1]} for {len(CASES)} case(s)")


if __name__ == "__main__":
    main()
